### ISSUE TITLE
[Feature request] Shared aliases

### ISSUE THREAD

**Issue by mdujava** [micharbet/CLE#12]
Idea:
CLE will manage some config file with aliases (let's say `cle sa ll="ls -la"`) and those aliases will be available on all sessions initiated from cle.

**Comment by micharbet** [comment]
Hi Matej,
Great idea, indeed! I'll add this feature in next release. (focussing on packaging now)
Thanks for this request.

**Comment by micharbet** [comment]
Hello Matej,
Done! Aliases are now transferred to live remote sessions! In fact aliasing was reworked, there are just basic ones (like `ls --colors=auto`) and it is up to the users to define their very own aliases. Those are then copied from CLE workstation to the remote session. Some of them might not work if the command is missing or accepts different options. Just redefine it. Local aliases override those inherited from workstation.

I hope this helps!
-michael-
