### ISSUE TITLE
CLE doesn't display /etc/motd

### ISSUE THREAD

**Issue by micharbet** [micharbet/CLE#15]
Message of the day should be displayed upon remote login. Some might find important information in it. reported by: @vhodina

**Comment by micharbet** [comment]
closed with commit 53ecf19

**Comment by vladki77** [comment]
I have found out that some systems (Ubuntu) may not have /etc/motd at all. Ubuntu uses a dynamic file /run/motd.dynamic instead (or prints them both). So a check for existence of /etc/motd would be nice (instead of displaying error)

**Comment by micharbet** [comment]
Ah! i missed this, excuses... will add /etc/motd check soon!

**Comment by micharbet** [comment]
Hi Vladki,
also this flaw has been fixed. Error message has been suppressed.

update and enjoy!
-michael-
