### ISSUE TITLE
"Alias" 'cle -h' and 'cle --help' to cle help

### ISSUE THREAD

**Issue by vasekhodina** [micharbet/CLE#20]
Here is an idea. Add options -h and --help to cle command, so that people don't have to remember that for help they need 'cle help' exactly. The option -h doesn't seem to be taken by anything else.

**Comment by micharbet** [comment]
Hi Vasku,

Thanks for idea. it's done + a bit more. 
Commit 6f64111

I'm closing this issue,
-michael-
