### ISSUE TITLE
cle color set not remembered (set to an empty string)

### ISSUE THREAD

**Issue by pericnenad** [micharbet/CLE#25]
When I tried to set a color for the prompt, it worked fine until I logged out. 
When i logged back in, the CLE complained about non-existent color. 

`# cle color yellow`
[0] 15:34 root xray136 ~ # 
 --- logged out ---

after logging in:

`Unknown color '' Select one of predefined:`

**Comment by micharbet** [comment]
Hi Nenad,
Thanks for heads-up!
Issue fixed in  78e247c, please do `cle update`

-michael-
