### ISSUE TITLE
Add full hostname to prompt

### ISSUE THREAD

**Issue by vladki77** [micharbet/CLE#41]
Hello Michal, 

thanks for nice presentation yesterday at OpenAlt. Consider this as a wishlist item:

Even during the presentation I asked about showing full hostname (FQDN) on the prompt. There is obvious solution to use standard bash "\H", but it is not working every time. At least in debian, it just shows whatever you have set in /etc/hostname, and that is by default only the first part of the hostname. All the rest is usually in /etc/resolv.conf as domain or search option. So what I really would appreciate is an option to put %H in prompt which would equal to `hostname -f`. 

The reason is that I maintain servers for different companies, and the names tend to repeat (mail.company.com, samba, hyperX, gate, ...) so I need to see the full name. 

So far I have to edit /etc/hostname to contain FQDN, and change \h to \H in PS1 definition in bashrc.

Best Regards
Vladki

**Comment by vladki77** [comment]
Well, I did it by myself, here is the necessary tweak file:

```
CLE_FHN=`hostname -f`
# CLE prompt escapes
_clesc () (
        C=_C$1
        P=CLE_P$1
        printf "\\[\$$C\\]"
        sed <<<${!P}\
         -e "s/%i/$CLE_IP/g"\
         -e "s/%h/$CLE_SHN/g"\
         -e "s/%H/$CLE_FHN/g"\
         -e "s/%u/$CLE_USER/g"\
         -e "s/%e/\\\[\$_CE\\\][\$_E]\\\[\$_CN\$$C\\\]/g"\
         -e "s/%c\(.\)/\\\[\\\$_C\1\\\]/g"\
         -e "s/%v\([[:alnum:]]*\)/\1=\$\1/g"
)

```

**Comment by micharbet** [comment]
Cool! Thanks Vladki,
This is exactly what I'd do :-)
I will add your snippet into clerc file as soon as I have time to dig into it.

KInd regards
-michael-

**Comment by vladki77** [comment]
I have some more tweaks, if you are interested.
- remove TLD from CLE_FHN
- changed format of CLE_WT (terminal window title)
- window title in uppercase for root sessions
- remove ourdomain from CLE_WT/CLE_P2

**Comment by micharbet** [comment]
Hi Vladki,
I added '%H' into clerc in slightly modified way - check latest commits and perform `cle update` I found strange behaviour of utility hostname with and without '-f' option. Workarounded and believe it's okay now
.
Next. I planned to work more on window titling. It can be helpful if you send me your suggestions. I will consider and either apply them into release Nova or the next one (Zodiac).
Also, what do you mean by removing 'ourdomain' resp. TLD. Attach the code please.

Thanks
-michael-

**Comment by vladki77** [comment]
The thing is that I want to see CLE_FHN for remote computers except for our own company (I put redhat there) where CLE_SHN would be enough. Also I found out that TLD (.cz, .com,..) is just wasting space. So my current setup is like this:

```
# get FQDN without TLD
CLE_FHN=`hostname -f|sed 's;\.[^.]*$;;'`

# default config
_defcf () {
        case $USER@$CLE_WS in
... unmodified ...
        esac
        CLE_P0='%e \A'
        CLE_P1='\u'
        CLE_P2='%H'
        CLE_P3='\w \$'
        [[ $CLE_FHN =~ redhat ]] && CLE_P2='%h'
}

# window title
_setwt () {
        CLE_WT=''
        [[ $TERM =~ linux ]] && return # no tits on console
        [[ $CLE_RC =~ remote ]] && CLE_WT="$CLE_USER -> " # never true
        CLE_WT=${CLE_FHN%.redhat}:
        [[ $USER = root ]] && CLE_WT=${CLE_WT^^}
}

```
I just wonder at what situation is CLE_RC matching "remote" ?
Also I consider username and pty number useless in window title.

**Comment by micharbet** [comment]
Hi Vladki,
Thank you very muich for comments and ideas!
- FQDN implemented via %H as suggested
 I haven't implemented 'our domain' removal It would require another configuration parameter rendering CLE more complex and even if I understand why you want it there I believe the two options CLE_SHN and CLE_FHN are sufficient in most of cases. Any other variants are quite easy doable in tweak file. Exactly like you did. And me too, here is snippet from my tweak file:
```
# tweak shortened hostname
# -remove xxx.phx2
# -uppercase PROD/STAGE/DEV
CLE_SHN=`sed \
        -e 's/.....phx2//' \
        -e 's/prod\|stage\|dev/\U&/' <<<$CLE_SHN`
```
Our FQDN is ridiculously long and from my perspective only its part is important + uppercasing the environment. I still can reconsider hostname shortening in future release, maybe in a way of pattern (regexp) removal.

- pty number removed from window title. not really necessary, thanks for this hint
I also left username in the title as I feel it is important to know what user runs shell inside. (e.g. I use 3-4 users on various boxes and need to know who's where) Nevertheless, for future, also window title string will be configurable in similar way like prompt. Stay tuned!

- and last but not least, that never-true-condition! Perfect catch! This was remainder from really old release where it was valid but not anymore :-D I had really to laugh looking at this!

So I feel like I can close this issue. All has been merged into master branch. Do not forget to run `cle update`
