### ISSUE TITLE
Warn on cle deploy when .bash_prompt is active

### ISSUE THREAD

**Issue by martinjansa** [micharbet/CLE#47]
Hi,

firstly, thanks for a great tool!

I am trying to use in on the HypriotOS, but strugged to get it working before I relalized that the OS itself comes with a custom ~/.bash_prompt, which sets the prompt colors. After the removal (rename) of the ~/.bash_prompt the CLE works great, it just took me some time to figure out the issue.

My environment:
    $ uname -a
    Linux proxy 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux

How to induce the problem.
1. login to an environment, where ~/.bash_prompt is created and called from ~/.profile
1. wget -O /tmp/clerc http://git.io/clerc
1. . /tmp/clerc
1. cle deploy
1. confirm the deployment with y

Output:
* the command prompt is not changed even after re-login

Expected behaviour:
* The ```cle deploy``` command warns the user that there is .bash_prompt which might collide with CLE.

Thank you,

Martin

**Comment by micharbet** [comment]
Hi Martin,
It's my pleasure if you like CLE! Thanks!

I was checking the .bash_prompt file. I must admit that I never heard of this and if not missed something important it's probably something HypriotOS specific. However I want to help also here.

Currently I have no time to install this system. Thus, I'm kindly asking you to point me to a repo where it grows to see what's inside this file and how it is really started. You mentioned it's started from .profile, I trust you... i believe we can find a way how to run CLE without altering the system. (I managed CLE to overload Powerline :-)

Also, important question:
Did CLE worked on this system as a remote live session?

Thanks for reporting!

-michael-

**Comment by micharbet** [comment]
Hi Martin,
I was checking startup sequence of CLE and still don't know why anything running from /etc/profile would affect this environment. Here is my reason: at the beginning of clerc there are two lines: 
```
_clexe /etc/profile
_clexe $HOME/.bashrc
```
and everything after them should (I believe) override system settings.

I'd like to ask you to answer my questions from previous message and also if you wish, you may try to disable one of those lines and check the behavior. Also, a copy of the file .bash_prompt would be nice to have and inspect. So you can be helpful here.

Cheers
-michael-

**Comment by micharbet** [comment]
Hi Martin,
I did some research in my freetime and found following startup files  from hypriot OS repository:
https://github.com/DieterReuter/make-rootfs-debian-arm64/tree/master/files/bash_prompt

I believed that I would be able to replicate your issue by simply adding them to my profile. But not. After running new shell I saw HypriotOS colorful prompt however when I tried to initiate CLE by command it simply did what was expected and changed the environment. The same happened when I used live ssh to the same host with HypriotOS profile files active - I could see how they were executed but it ended up like CLE session anyway.

Simply to say: having those files I see the .bash_profile is executed from .profile but  none of these affected CLE in any way. 

Not sure what's happening on your side. I'm really curious,
Would you please tell me if the linked files are the same you have on your system? From where exactly is the conflicting .bash_prompt executed? Is it /etc/prompt or $HOME/.prompt ? 

Cheers
-michael-

**Comment by micharbet** [comment]
Martin,
maybe it would be nice if you add following line:
`echo STARTUP: $BASH_SOURCE`
at the beginning of startup files on the hypriotos. Like into /etc/profile, $HOME/.profile, $HOME/.bashrc $HOME/.bash_profile and whatever is started upon login. You can as well do the same to CLE resource file. Such you can see how files are executed, like here is my example:

```
 [0] mich stalker.usersys  
18:01 ~: >>> lssh mich@localhost
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
STARTUP: /home/mich/.cle-mich/rc-stalker.usersys.redhat.com
STARTUP: /home/mich/.cle-mich/rc-stalker.usersys.redhat.com
STARTUP: /etc/profile
STARTUP: /etc/bashrc
STARTUP: /home/mich/.profile
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
STARTUP: /home/mich/.bash_prompt
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc

18:01:38 up 4 days, 6:52, 2 users, load average: 1.34, 1.87, 1.95

 [0] mich stalker.usersys (127.0.0.1) 
18:01 ~: >>> 
```
See that the file .bash_profile is executed but cle started anyway. On the other hand, cle is not started upon plain (non live) ssh session:

```
 [0] mich stalker.usersys  
18:05 ~: >>> ssh mich@localhost
Last login: Tue Dec 11 18:01:37 2018 from 127.0.0.1
STARTUP: /etc/profile
STARTUP: /etc/bashrc
STARTUP: /home/mich/.profile
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
STARTUP: /home/mich/.bash_prompt
STARTUP: /home/mich/.bash_profile
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
STARTUP: /home/mich/.bash_prompt
HypriotOS: mich@stalker.usersys.redhat.com in ~
$ 
```
And then runs properly when initiated manually:
```
HypriotOS: mich@stalker.usersys.redhat.com in ~
$ . d/CLE/clerc
STARTUP: /etc/profile
STARTUP: /etc/bashrc
STARTUP: /home/mich/.profile
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
STARTUP: /home/mich/.bash_prompt
STARTUP: /home/mich/.bashrc
STARTUP: /etc/bashrc
 It seems you started CLE running '/home/mich/.cle-mich/rc1'
 Since this is the first run, consider setup in your profile.
 Following command will hook CLE in /home/mich/.bashrc:
	cle deploy

 [0] mich stalker.usersys (127.0.0.1) 
18:07 ~: >>> 
```

I would like you to try something similar and send me your results for analysis.

Thank you in advance.
-michael-

**Comment by micharbet** [comment]
No communication, closing this issue
