### ISSUE TITLE
Error on startup on Mac OS

### ISSUE THREAD

**Issue by KubqoA** [micharbet/CLE#6]
When starting new instance of cle on the new version on Mac OS, this error happens:

> readlink: illegal option -- f
> usage: readlink [-n] [file ...]

**Comment by micharbet** [comment]
resolved with this:
```
CLE_RC=${BASH_SOURCE[0]}
CLE_DRC=$(cd `dirname $CLE_RC`; pwd;)
CLE_RC=$CLE_DRC/`basename $CLE_RC`
```
