### ISSUE TITLE
Chování v rámci shellu v Midnight Commanderu

### ISSUE THREAD

**Issue by milansie** [micharbet/CLE#75]
If there is mc started in CLE, and any command in it - there is an error (even if command is processed correctly):

```
[0] 12:56:31 msiebenb  ~ $ date
St 14. října 2020, 12:56:32 CEST
bash: [: příliš mnoho argumentů
[0] 12:56:32 msiebenb  ~ $ 
```

Milan Siebenbürger

**Comment by mdujava** [comment]
line causing this error: https://github.com/micharbet/CLE/blob/6fbd400b1184199118d12117061f10f776bbf427/clerc#L372
in case of running mc and going to shell with `<C>+o`, `$PROMPT_COMMAND` is set to `pwd>&9;kill -STOP $$`. After following shellcheck `SC2086: Double quote to prevent globbing and word splitting.` looks like error no longer appear. 

Is there and intention to use globing/word splitting?

**Comment by micharbet** [comment]
Hello Matej and Milan,
Yes, this is exactly where the error occurs. Good catch, thank you!
I've been dealing dealing with the issue over the weekend  and still not finished. Bash becomes tricky when pushed to the edge like in this case. See:
1. **I fixed it** for now by adding double quotes. It's pushed to the repository so you can run `cle update` to refresh the environment. It will report no error in Midnight commander but it has side efect
2. look at rich history, there will be repeating  commands when you push enter on empty line.
3. time calculations might be broken too
Above issues appear only in CLE inside MC, regular shell session works properly. This is better than the error reported here but I'm not closing the issue as it still bothers me.

Further analysis: the line `[ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return` is used to identify if a real command was issued, I found no better way so far. Unfortunately MC adds own commands to the $PROMPT_COMMAND. The string can become something like `PROMPT_COMMAND=$'precmd\npwd>&12;kill -STOP $$` which effectively messes up with CLE and causes the above mentioned side effects.

Stay tuned!

**Comment by mdujava** [comment]
This part: `pwd>&12;kill -STOP $$` is changing dir of the last focues pane. 

In normal shell on enter press `$BASH_COMMAND` and `$PROMPT_COMMAND` are `precmd`.  
But in mc `BASH_COMMAND='pwd 1>&9'` and `PROMPT_COMMAND='precmd\npwd>&9;kill -STOP $$'`

**Comment by micharbet** [comment]
Hello,
Ther is commit 260ecde fixing this issue with a new way of how to identify an issued command. Please kindly check the commit message and enhanced comments in source file clerc.sh.
Of course do not forget `cle update` :-) 

Thanks for reporting and your comments guys!
-michael-
