### ISSUE TITLE
"Open in Terminal" goes to home directory of current user. 

### ISSUE THREAD

**Issue by bhushansahane** [micharbet/CLE#77]
When using `open in terminal` option from right click menu in File Explorer always start the terminal with `/home/user` as working directory.

**Comment by micharbet** [comment]
Hi Bhushan,
The issue is fixed. Please do `cle update` to get fresh environment.
And, Thank you for reporting!
-michael-

commit: db1c9d6dff925fe671fd5b156047c75d85e4ec3d

**Comment by bhushansahane** [comment]
Thank You Sir for help
