### ISSUE TITLE
conflict with .bash_aliases

### ISSUE THREAD

**Issue by vladki77** [micharbet/CLE#79]
Some systems have this code in .bashrc by default:

```
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

```
The problem is if there are aliases defined which happen to have the same names as functions defined by CLE.   Although there is `unalias aa h hh .. ...` at the beginning of CLE/rc, it runs ~/.bashrc later and thus all stuff from .bash_aliases is created.

IMHO the `unalias ...` should be called after sourcing ~/.bashrc (or any external file that could introduce any aliases), or even better, call unalias before defining any internal function. (And best would be to print a warning if an alias was really removed, so the user knows that his good old alias was overriden by CLE).

Exaples I found so far are `..` `...` (with the same meaning as in CLE) and `vdump` = `virsh dump`

**Comment by micharbet** [comment]
Hi Vladki, small cleanup I should have done before Christmas...
I think this can be closed. THank you for all your reports and discusssions
=michael=
