### ISSUE TITLE
clerc complains about bash-completion package

### ISSUE THREAD

**Issue by savitojs** [micharbet/CLE#81]
It would be nice if CLE detects the missing required packages or ask permission to install them.

```bash
[savitoj@savitoj-test ~]$ . clerc
-bash: /usr/share/bash-completion/bash_completion: No such file or directory
 It seems you started CLE running '/home/savitoj/.cle-savitoj/rc1' from command line
 Since this is the first run, consider setup in your profile.
```

cc: @micharbet

**Comment by micharbet** [comment]
Hi Savitoj,
try to get new version with `cle update`
The error message for completion should not appear anymore.

**Comment by savitojs** [comment]
@micharbet Works perfectly for me after the update. Thank you Mich
